name: EnvironmentalDependentLimit
description: This is a environmental based limit dependency model for calculating operational limits.
ancestors:
- LimitDependency
descendents:
- TemperaturePolynomialLimit
- TemperatureDependentLimitTable